import { normalizeCaptureDefinition } from "./captureValidation";
import type { Header, QualityGate, ScenarioStep, StartRequest } from "./types";
import {
  sanitizeHeaderRows,
  sanitizeSensitiveURL,
  sanitizeStructuredBody,
} from "./secretSanitization";

export function downloadK6Script(request: StartRequest) {
  const blob = new Blob([buildK6Script(request)], { type: "text/javascript" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = k6Filename(request.config.url);
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildK6Script(request: StartRequest) {
  const steps = scenarioSteps(request);
  validateK6Compatibility(request, steps);
  validateTemplateOrder(steps);
  const lines = [
    ...renderParityNotes(request),
    "import http from \"k6/http\";",
    "import { check, sleep } from \"k6\";",
    "",
    "export const options = {",
    ...renderExecutionOptions(request),
    ...renderThresholds(request.qualityGate),
    "};",
    "",
  ];

  lines.push(
    "const runVars = {};",
    "const owns = (value, name) => Object.prototype.hasOwnProperty.call(value, name);",
    "const resolve = (name, iterationVars) => {",
    "  if (owns(iterationVars, name)) return iterationVars[name];",
    "  if (owns(runVars, name)) return runVars[name];",
    "  if (name.startsWith(\"SECRET_\") && owns(__ENV, name)) return __ENV[name];",
    "  throw new Error(`Template variable ${name} is unavailable for this iteration`);",
    "};",
    "const render = (value, iterationVars) => value.replace(/\\{\\{([^}]+)\\}\\}/g, (_match, name) => resolve(name.trim(), iterationVars));",
    "const matchesStatus = (status, policy) => policy === \"any\" ||",
    "  (policy === \"success\" && status >= 200 && status < 400) ||",
    "  (/^[1-5]xx$/.test(policy) && Math.floor(status / 100) === Number(policy[0])) ||",
    "  (/^[1-5][0-9]{2}$/.test(policy) && status === Number(policy));",
    "const pathSegments = (path) => path === \"$\" ? [] : path.replace(/^\\$\\.?/, \"\").replace(/\\[(\\d+)\\]/g, (_match, index) => `.${String(Number(index))}`).split(\".\").filter(Boolean);",
    "const captureAll = (captures, response, iterationVars) => {",
    "  const eligible = captures.filter(({ name, scope, onStatus }) => {",
    "    if (scope === \"run\" && owns(runVars, name)) return false;",
    "    if (matchesStatus(response.status, onStatus)) return true;",
    "    if (scope === \"iteration\") delete iterationVars[name];",
    "    return false;",
    "  });",
    "  if (eligible.length === 0) return true;",
    "  try {",
    "    const document = response.json();",
    "    const values = eligible.map(({ path }) => pathSegments(path).reduce((current, segment) => {",
    "      if (current == null) return undefined;",
    "      const key = Array.isArray(current) && /^\\d+$/.test(segment) ? Number(segment) : segment;",
    "      return current[key];",
    "    }, document));",
    "    if (values.some((value) => value === undefined)) throw new Error(\"capture path not found\");",
    "    eligible.forEach(({ name, scope }, index) => {",
    "      const value = values[index];",
    "      const rendered = typeof value === \"string\" ? value : value == null ? \"\" : typeof value === \"object\" ? JSON.stringify(value) : String(value);",
    "      (scope === \"run\" ? runVars : iterationVars)[name] = rendered;",
    "    });",
    "    return true;",
    "  } catch (_error) {",
    "    eligible.forEach(({ name, scope }) => { if (scope === \"iteration\") delete iterationVars[name]; });",
    "    return false;",
    "  }",
    "};",
    "",
  );

  lines.push("export default function () {", "  const iterationVars = {};", "  let res;");
  const requestTimeout = formatK6Duration(request.config.requestTimeoutMs);
  for (const step of steps) {
    lines.push(...renderStep(step, requestTimeout));
  }
  lines.push("}", "");
  return `${lines.join("\n")}`;
}

function renderParityNotes(request: StartRequest) {
  const notes = [
    "// Generated by FlowRoutine. Compatibility notes:",
    "// - k6 checks mirror capture and status assertions without changing HTTP failure-rate thresholds.",
    "// - k6 samples every request; FlowRoutine sampling, connection buffers, and response-size limits have no direct equivalent.",
  ];
  if (request.config.rateLimitRps > 0) {
    notes.push(
      "// - The k6 global rps option preserves FlowRoutine request pacing on one load generator.",
      "//   k6 applies rps independently per generator in cloud or distributed runs.",
    );
  }
  if (request.config.rampUpMs > 0 && request.config.virtualUsers > 1) {
    notes.push("// - ramping-vus approximates FlowRoutine's discrete per-worker startup schedule.");
  } else if (request.config.rampUpMs > 0) {
    notes.push("// - Ramp-up is omitted because FlowRoutine starts its only VU immediately.");
  }
  notes.push("");
  return notes;
}

function renderExecutionOptions(request: StartRequest) {
  const {
    durationMs,
    rampUpMs,
    rateLimitRps,
    requestTimeoutMs,
    virtualUsers,
  } = request.config;
  const scenario = [
    "  scenarios: {",
    "    flowroutine: {",
  ];
  if (rampUpMs > 0 && virtualUsers > 1) {
    scenario.push(
      "      executor: \"ramping-vus\",",
      "      startVUs: 1,",
      "      stages: [",
      `        { duration: ${JSON.stringify(formatK6Duration(rampUpMs))}, target: ${virtualUsers} },`,
    );
    const steadyDurationMs = durationMs - rampUpMs;
    if (steadyDurationMs > 0) {
      scenario.push(
        `        { duration: ${JSON.stringify(formatK6Duration(steadyDurationMs))}, target: ${virtualUsers} },`,
      );
    }
    scenario.push("      ],");
  } else {
    scenario.push(
      "      executor: \"constant-vus\",",
      `      vus: ${virtualUsers},`,
      `      duration: ${JSON.stringify(formatK6Duration(durationMs))},`,
    );
  }
  scenario.push(
    `      gracefulStop: ${JSON.stringify(formatK6Duration(requestTimeoutMs))},`,
    "    },",
    "  },",
  );
  if (rateLimitRps > 0) {
    scenario.push(`  rps: ${rateLimitRps},`);
  }
  return scenario;
}

function renderThresholds(gate: QualityGate | undefined) {
  const thresholds: string[] = [];
  const maxFailureRatePct = nonNegative(gate?.maxFailureRatePct, 1);
  const maxP95LatencyMs = nonNegative(gate?.maxP95LatencyMs, 500);
  const maxP99LatencyMs = nonNegative(gate?.maxP99LatencyMs, 1000);
  const minRps = nonNegative(gate?.minRps, 0);
  if (maxFailureRatePct > 0) {
    thresholds.push(`    http_req_failed: [${JSON.stringify(`rate<=${maxFailureRatePct / 100}`)}],`);
  }
  const latencyThresholds = [];
  if (maxP95LatencyMs > 0) {
    latencyThresholds.push(`p(95)<=${maxP95LatencyMs}`);
  }
  if (maxP99LatencyMs > 0) {
    latencyThresholds.push(`p(99)<=${maxP99LatencyMs}`);
  }
  if (latencyThresholds.length > 0) {
    thresholds.push(`    http_req_duration: [${latencyThresholds.map((item) => JSON.stringify(item)).join(", ")}],`);
  }
  if (minRps > 0) {
    thresholds.push(`    http_reqs: [${JSON.stringify(`rate>=${minRps}`)}],`);
  }
  if (thresholds.length === 0) {
    return [];
  }
  return [
    "  thresholds: {",
    ...thresholds,
    "  },",
  ];
}

function scenarioSteps(request: StartRequest): ScenarioStep[] {
  const steps = request.config.scenarioSteps.length > 0
    ? request.config.scenarioSteps
    : [{
        kind: "request" as const,
        url: request.config.url,
        method: request.config.method,
        headers: request.config.headers,
        body: request.config.body,
      }];
  const captureNames = new Set(
    steps.flatMap((step) => (step.captures ?? []).map((capture) => capture.name.trim())),
  );
  return steps.map((step) => sanitizeScenarioStep(step, captureNames));
}

function sanitizeScenarioStep(
  step: ScenarioStep,
  captureNames: ReadonlySet<string>,
): ScenarioStep {
  if (step.kind !== "request") {
    return step;
  }
  return {
    ...step,
    url: sanitizeSensitiveURL(step.url ?? "", captureNames),
    headers: sanitizeHeaderRows(step.headers ?? [], captureNames),
    body: sanitizeStructuredBody(step.body ?? "", captureNames),
  };
}

function renderStep(step: ScenarioStep, requestTimeout: string) {
  switch (step.kind) {
    case "request":
      return renderRequestStep(step, requestTimeout);
    case "delay":
      return [`  sleep(${secondsLiteral(step.delayMs ?? 0)});`];
    case "assertStatus":
      return renderStatusCheck(step.expectedStatus ?? "2xx");
  }
}

function renderRequestStep(step: ScenarioStep, requestTimeout: string) {
  const method = step.method || "GET";
  const body = step.body ? `render(${JSON.stringify(step.body)}, iterationVars)` : "null";
  const lines = [
    `  res = http.request(${JSON.stringify(method)}, render(${JSON.stringify(step.url || "")}, iterationVars), ${body}, {`,
    `    headers: ${renderHeaders(step.headers ?? [], "    ")},`,
    `    timeout: ${JSON.stringify(requestTimeout)},`,
    "  });",
  ];
  const captures = (step.captures ?? []).map(normalizeCaptureDefinition);
  if (captures.length > 0) {
    const label = `captures: ${captures.map((capture) => capture.name).join(", ")}`;
    lines.push(
      "  check(res, {",
      `    ${JSON.stringify(label)}: (response) => captureAll(${JSON.stringify(captures)}, response, iterationVars),`,
      "  });",
    );
  }
  return lines;
}

function renderHeaders(headers: Header[], baseIndent: string) {
  const activeHeaders = headers.filter((header) => header.name.trim());
  if (activeHeaders.length === 0) {
    return "{}";
  }
  const entries = activeHeaders.map((header) => {
    return `${baseIndent}  ${JSON.stringify(header.name)}: render(${JSON.stringify(header.value)}, iterationVars),`;
  });
  return `{\n${entries.join("\n")}\n${baseIndent}}`;
}

function validateTemplateOrder(steps: ScenarioStep[]) {
  const available = new Map<string, "iteration" | "run">();
  for (const [index, step] of steps.entries()) {
    if (step.kind !== "request") {
      continue;
    }
    if (templateNames(step.method ?? "").length > 0) {
      throw new Error(`Scenario step ${index + 1} method cannot contain templates`);
    }
    if (templateNames(urlAuthority(step.url ?? "")).length > 0) {
      throw new Error(`Scenario step ${index + 1} host cannot contain templates`);
    }
    for (const header of step.headers ?? []) {
      if (templateNames(header.name).length > 0) {
        throw new Error(`Scenario step ${index + 1} header names cannot contain templates`);
      }
    }
    for (const value of [
      step.url ?? "",
      step.body ?? "",
      ...(step.headers ?? []).map((header) => header.value),
    ]) {
      for (const name of templateNames(value)) {
        if (!name.startsWith("SECRET_") && !available.has(name)) {
          throw new Error(`Scenario step ${index + 1} template variable ${name} is not defined by an earlier capture`);
        }
      }
    }
    const stepNames = new Set<string>();
    for (const rawCapture of step.captures ?? []) {
      const capture = normalizeCaptureDefinition(rawCapture);
      if (stepNames.has(capture.name)) {
        throw new Error(`Capture name ${capture.name} is duplicated in scenario step ${index + 1}`);
      }
      stepNames.add(capture.name);
      const scope = capture.scope;
      const existingScope = available.get(capture.name);
      if (existingScope && existingScope !== scope) {
        throw new Error(`Capture ${capture.name} changes scope from ${existingScope} to ${scope}`);
      }
      available.set(capture.name, scope);
    }
  }
}

function validateK6Compatibility(request: StartRequest, steps: ScenarioStep[]) {
  const {
    durationMs,
    rampUpMs,
    rateLimitRps,
    requestTimeoutMs,
    virtualUsers,
  } = request.config;
  requirePositiveSafeInteger("Virtual users", virtualUsers);
  requirePositiveSafeInteger("Duration", durationMs);
  requirePositiveSafeInteger("Request timeout", requestTimeoutMs);
  requireNonNegativeSafeInteger("Ramp-up", rampUpMs);
  requireNonNegativeSafeInteger("Rate limit RPS", rateLimitRps);
  if (rampUpMs > durationMs) {
    throw new Error(
      `k6 export requires ramp-up (${rampUpMs}ms) to be no longer than duration (${durationMs}ms)`,
    );
  }

  let requestSteps = 0;
  for (const [index, step] of steps.entries()) {
    switch (step.kind) {
      case "request":
        requestSteps += 1;
        if (!(step.url ?? "").trim()) {
          throw new Error(`Scenario step ${index + 1} request URL is required for k6 export`);
        }
        break;
      case "delay":
        requireNonNegativeSafeInteger(`Scenario step ${index + 1} delay`, step.delayMs ?? 0);
        break;
      case "assertStatus":
        if (!(step.expectedStatus ?? "").trim()) {
          throw new Error(`Scenario step ${index + 1} expected status is required for k6 export`);
        }
        break;
      default:
        throw new Error(
          `Scenario step ${index + 1} has unsupported kind ${String((step as { kind?: unknown }).kind)}`,
        );
    }
  }
  if (requestSteps === 0) {
    throw new Error("k6 export requires at least one request step");
  }
}

function requirePositiveSafeInteger(label: string, value: number) {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${label} must be a positive integer for k6 export`);
  }
}

function requireNonNegativeSafeInteger(label: string, value: number) {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new Error(`${label} must be a non-negative integer for k6 export`);
  }
}

function urlAuthority(rawURL: string) {
  return rawURL.match(/^[a-z][a-z0-9+.-]*:\/\/([^/?#]*)/i)?.[1] ?? "";
}

function templateNames(value: string) {
  const names: string[] = [];
  let offset = 0;
  while (offset < value.length) {
    const start = value.indexOf("{{", offset);
    const unexpectedClose = value.indexOf("}}", offset);
    if (start < 0) {
      if (unexpectedClose >= 0) {
        throw new Error("Template contains an unexpected closing delimiter");
      }
      break;
    }
    if (unexpectedClose >= 0 && unexpectedClose < start) {
      throw new Error("Template contains an unexpected closing delimiter");
    }
    const end = value.indexOf("}}", start + 2);
    if (end < 0) {
      throw new Error("Template contains an unclosed variable");
    }
    const name = value.slice(start + 2, end).trim();
    if (!name) {
      throw new Error("Template variable name is required");
    }
    if (!/^[a-z_][a-z0-9_.-]*$/i.test(name)) {
      throw new Error(`Invalid template variable name: ${name}`);
    }
    names.push(name);
    offset = end + 2;
  }
  return names;
}

function renderStatusCheck(expectedStatus: string) {
  const expected = expectedStatus.trim() || "2xx";
  if (/^[1-5]xx$/.test(expected)) {
    const lower = Number(expected[0]) * 100;
    const upper = lower + 100;
    return [
      "  check(res, {",
      `    ${JSON.stringify(`status is ${expected}`)}: (response) => response != null && response.status >= ${lower} && response.status < ${upper},`,
      "  });",
    ];
  }
  if (/^\d{3}$/.test(expected)) {
    return [
      "  check(res, {",
      `    ${JSON.stringify(`status is ${expected}`)}: (response) => response != null && response.status === ${Number(expected)},`,
      "  });",
    ];
  }
  return [
    "  check(res, {",
    `    ${JSON.stringify(`status is ${expected}`)}: (response) => response != null && String(response.status) === ${JSON.stringify(expected)},`,
    "  });",
  ];
}

function formatK6Duration(valueMs: number) {
  const ms = Math.max(1, Math.floor(valueMs));
  if (ms % 60_000 === 0) {
    return `${ms / 60_000}m`;
  }
  if (ms % 1_000 === 0) {
    return `${ms / 1_000}s`;
  }
  return `${ms}ms`;
}

function secondsLiteral(valueMs: number) {
  return Number((Math.max(0, valueMs) / 1_000).toFixed(3));
}

function nonNegative(value: number | undefined, fallback: number) {
  return typeof value === "number" && Number.isFinite(value) ? Math.max(0, value) : fallback;
}

function k6Filename(rawURL: string) {
  const host = safeHost(rawURL);
  return `flowroutine-${host}.k6.js`;
}

function safeHost(rawURL: string) {
  try {
    return new URL(rawURL).host.replace(/[^a-z0-9.-]+/gi, "-").slice(0, 64) || "scenario";
  } catch {
    return "scenario";
  }
}
